---

- name: collect the instance facts
  ec2_facts:
  register: current_instance

- name: add the instances to the auto scaling group 
  shell: "/home/ec2-user/.local/bin/aws autoscaling attach-instances --instance-ids {{ current_instance.ansible_facts.ansible_ec2_instance_id }} --auto-scaling-group-name {{ asg_name }}"
 
# aws autoscaling attach-instances --instance-ids i-a8e09d9c --auto-scaling-group-name my-asg
