---
- name: unhook the resources on server 3
  hosts: rs_servers[2]
  tasks:
  - include_role:
      name: create_image
      tasks_from: "unhook_resources"

- name: invoke the create image role
  hosts: local
  vars:
    - ami_name: "ami3_skamon_demoapp_rs"
    - lc_name: "lc3_skamon_demoapp_rs"
    - private_dns: "{{ hostvars[groups.rs_servers[2]].private_dns }}"
  roles:
    - role: create-image
    - role: launch-configuration
    - role: auto-scaling-group
      asg_name: "asg3_skamon_demoapp_rs"

- name: hookup the resources on server 3
  hosts: rs_servers[2]
  tasks:
  - include_role:
      name: create-image
      tasks_from: "hookup_resources"

- name: attach the instance ids to the auto-scaling-group
  hosts: rs_servers
  vars:
    - asg_name: "asg3_skamon_demoapp_rs"
  tasks:
    - include_role:
        name: auto-scaling-group
        tasks_from: "attach"
