---
- name: display the primary hostname, replicaset name, mongo port and members
  debug: msg="inventory_hostname [{{inventory_hostname}}], replicaset [{{replset_name}}], mongo_port [{{mongo_port}}] members [{{members}}]"

- name: initiate replica set with all the members and wait 5 sec
  shell: "mongo admin --port {{mongo_port}} --eval 'rs.initiate({_id: \"{{replset_name}}\", members: [{_id:0, host: \"{{members[0]}}\"}, {_id:1, host: \"{{members[1]}}\"}, {_id:2, host: \"{{members[2]}}\"} ]});sleep(5000);'"
